/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/sysinit.o
tr.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/system.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/lnfodwrf.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/exeinfo.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/strings.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/objpas.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/cthreads.o
country9.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/dos.o
fcontest.o
jctrl1.o
jctrl2.o
cfgcmd.o
logcfg.o
logcw.o
logdom.o
logdupe.o
logddx.o
logedit.o
loggrid.o
loghelp.o
loghp.o
logmenu.o
logpack.o
logprom.o
logqsonr.o
logscp.o
logstuff.o
logudp.o
logwae.o
logwind.o
n1mm.o
n4ogw.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl-extra/printer.o
twobsiq.o
trcrt.o
slowtree.o
tree.o
dupe.o
zonecont.o
logk1ea.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/baseunix.o
memlinux.o
linuxsound.o
timer.o
datetimec.o
dt.o
beep.o
foot.o
xkb.o
radio.o
so2r.o
keycode.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/libcurl/libcurl.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/sysutils.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/unix.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/unixtype.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/initc.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/sysctl.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/unixutil.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/ctypes.o
communication.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl-extra/sockets.o
portname.o
findports.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/termio.o
ieee1284.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/errors.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/sysconst.o
lowlatency.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/objc.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/objcbase.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/classes.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/cocoaint/CocoaAll.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/fcl-process/process.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/types.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/typinfo.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/rtlconsts.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/math.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/cocoaint/DefinedClassesFoundation.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/cocoaint/DefinedClassesCoreImage.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/cocoaint/DefinedClassesQuartzCore.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/cocoaint/DefinedClassesCoreData.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/cocoaint/DefinedClassesAppKit.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/univint/MacOSAll.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/macpas.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/blockrtl.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/univint/MacTypes.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/univint/CoreAudioTypes.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/fcl-process/pipes.o
keyerard.o
keyerk1ea.o
keyerwin.o
keyers.o
keyeryccc.o
footyccc.o
footard.o
rig.o
scorereporter.o
scoreposter.o
ycccprotocol.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/cwstring.o
hidp.o
hid.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/dynlibs.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/unixcp.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl/dl.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/fcl-xml/dom.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/fcl-xml/xmlwrite.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/fcl-xml/xmlutils.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/fcl-xml/dtdmodel.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/fcl-base/uriparser.o
k1eanet.o
logsort.o
kenwood.o
icom.o
rigctld.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/rtl-objpas/strutils.o
tbsiq_cw.o
tbsiq_subs.o
blcksock.o
synafpc.o
synsock.o
synautil.o
synacode.o
synaip.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/fcl-base/syncobjs.o
/opt/homebrew/Cellar/fpc/3.2.2_1/lib/fpc/3.2.2/units/aarch64-darwin/fcl-net/netdb.o
